### PR TITLE
Update package-lock.json

### PR DESCRIPTION
**Pull request by nickmccurdy**
I got local changes to `package-lock.json` that haven't been committed. I also had to `npm install` a second time to fix a missing dependency, which was strange. Hopefully this should prevent that sort of issue in production.

### CODE REVIEW

**Comment by vcarl** [comment]
I think this is gonna keep happening while discord.js is loaded as `"discord.js": "https://github.com/discordjs/discord.js.git",`

**Comment by nickmccurdy** [comment]
I thought the git ref was supposed to be locked into `package-lock.json` as well. I assumed that someone updated package.json or partially updated package-lock.json without committing the rest of package-lock.json.

**Comment by nickmccurdy** [comment]
As long as that PR didn’t change versions beyond these changes or removing packages, I’m fine with closing this

**Comment by nickmccurdy** [comment]
Completed when #60 was merged, there's no diff now

**Pull request closed without merging**
