### PR TITLE
Add snack.io to code options

### PR DESCRIPTION
**Pull request by rahsheen**

### CODE REVIEW

**Comment by nickmccurdy** [comment]
Good idea!

Is it supposed to default to web or should be override that?

**Comment by rahsheen** [comment]
I think it always defaults to web, but maybe there's a way around that. Will check.

**Comment by nickmccurdy** [comment]
You're more familiar with React Native than I am. I'm not just sure if that's common for React Native Expo developers, or if it's specifically for web developers.

**Comment by nickmccurdy** [comment]
We can merge this and figure out the default mode thing later if it's an issue.

**Pull request merged**
